import { useEffect, useMemo, useRef, useState, useCallback } from "react";
import type { Chart, ChartNote, ChartDifficulty, NoteType, ChartValidationError } from "./types";
import {
  getChartForSong,
  validateChart,
  normalizeChartNotes,
  recalculateChartStats,
  saveCustomChart,
  restoreAutoGeneratedChart,
  getAutoGeneratedChart,
  isChartCustom,
  CHART_DIFFICULTIES,
  CHART_DIFFICULTY_INFO,
} from "./charts";
import { formatDuration } from "./songs";
import { resourceManager } from "./resourceManager";

interface ChartEditorProps {
  songId: string;
  initialDifficulty: ChartDifficulty;
  onBack: () => void;
}

const TRACK_COUNT = 4;
const TRACK_COLORS = ["#4f46e5", "#06b6d4", "#f97316", "#ec4899"];
const DENSITY_WINDOW_MS = 2000;
const DEFAULT_VIEWPORT_SECONDS = 30;
const ZOOM_LEVELS = [15, 30, 60, 120];
const NOTE_SNAP_MS = 50;

type EditorTool = "select" | "add-tap" | "add-long" | "delete";

export default function ChartEditor({
  songId,
  initialDifficulty,
  onBack,
}: ChartEditorProps) {
  const song = resourceManager.getSongById(songId);
  const [difficulty, setDifficulty] = useState<ChartDifficulty>(initialDifficulty);
  const [chart, setChart] = useState<Chart>(() => getChartForSong(songId, initialDifficulty));
  const [notes, setNotes] = useState<ChartNote[]>(() => [...getChartForSong(songId, initialDifficulty).notes]);
  const [selectedNoteId, setSelectedNoteId] = useState<number | null>(null);
  const [currentTool, setCurrentTool] = useState<EditorTool>("select");
  const [viewportLeft, setViewportLeft] = useState(0);
  const [viewportSeconds, setViewportSeconds] = useState(DEFAULT_VIEWPORT_SECONDS);
  const [containerWidth, setContainerWidth] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStartX, setDragStartX] = useState(0);
  const [dragStartLeft, setDragStartLeft] = useState(0);
  const [isDraggingNote, setIsDraggingNote] = useState(false);
  const [dragNoteId, setDragNoteId] = useState<number | null>(null);
  const [dragNoteOffset, setDragNoteOffset] = useState(0);
  const [isResizingLong, setIsResizingLong] = useState(false);
  const [resizeNoteId, setResizeNoteId] = useState<number | null>(null);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [validationErrors, setValidationErrors] = useState<ChartValidationError[]>([]);
  const [showValidation, setShowValidation] = useState(false);

  const containerRef = useRef<HTMLDivElement>(null);
  const tracksRef = useRef<HTMLDivElement>(null);
  const densityRef = useRef<HTMLDivElement>(null);

  const TRACK_LABEL_WIDTH = 36;

  const totalDurationMs = song ? song.duration * 1000 : 0;
  const viewportDurationMs = Math.min(viewportSeconds * 1000, totalDurationMs);
  const viewportZoomIndex = ZOOM_LEVELS.indexOf(viewportSeconds);
  const canZoomIn = viewportZoomIndex > 0;
  const canZoomOut = viewportZoomIndex < ZOOM_LEVELS.length - 1 && viewportSeconds * 1000 < totalDurationMs;

  useEffect(() => {
    const newChart = getChartForSong(songId, difficulty);
    setChart(newChart);
    setNotes([...newChart.notes]);
    setSelectedNoteId(null);
    setHasUnsavedChanges(false);
    setValidationErrors([]);
    setShowValidation(false);
    setViewportLeft(0);
  }, [songId, difficulty]);

  useEffect(() => {
    const measure = () => {
      if (containerRef.current) {
        const rect = containerRef.current.getBoundingClientRect();
        setContainerWidth(rect.width);
      }
    };
    measure();
    const ro = typeof ResizeObserver !== "undefined" ? new ResizeObserver(measure) : null;
    if (ro && containerRef.current) {
      ro.observe(containerRef.current);
    }
    return () => {
      if (ro) ro.disconnect();
    };
  }, []);

  const pxPerMs = useMemo(() => {
    if (containerWidth <= 0 || viewportDurationMs <= 0) return 0;
    return containerWidth / viewportDurationMs;
  }, [containerWidth, viewportDurationMs]);

  const maxLeft = Math.max(0, totalDurationMs - viewportDurationMs);

  useEffect(() => {
    setViewportLeft((prev) => Math.min(prev, maxLeft));
  }, [maxLeft]);

  const stats = useMemo(() => {
    const totalNotes = notes.length;
    const tapNotes = notes.filter((n) => n.type === "tap").length;
    const longNotes = notes.filter((n) => n.type === "long").length;
    const trackDistribution = [0, 0, 0, 0];
    for (const note of notes) {
      if (note.track >= 0 && note.track < TRACK_COUNT) {
        trackDistribution[note.track]++;
      }
    }
    const totalDuration = notes.length > 0
      ? Math.max(...notes.map((n) => n.type === "long" && n.duration ? n.time + n.duration : n.time))
      : 0;
    const density = totalDuration > 0 ? (totalNotes / (totalDuration / 1000)) : 0;

    return {
      totalNotes,
      tapNotes,
      longNotes,
      trackDistribution,
      density: density.toFixed(2),
    };
  }, [notes]);

  const densityData = useMemo(() => {
    const windows: { time: number; count: number }[] = [];
    const step = DENSITY_WINDOW_MS / 2;
    for (let t = 0; t < totalDurationMs; t += step) {
      const windowStart = t;
      const windowEnd = t + DENSITY_WINDOW_MS;
      let count = 0;
      for (const note of notes) {
        if (note.time >= windowStart && note.time < windowEnd) {
          count++;
        }
      }
      windows.push({ time: t + DENSITY_WINDOW_MS / 2, count });
    }
    const maxCount = Math.max(...windows.map((w) => w.count), 1);
    return windows.map((w) => ({
      time: w.time,
      density: w.count / maxCount,
      isPeak: w.count / maxCount > 0.7,
    }));
  }, [notes, totalDurationMs]);

  const peakSections = useMemo(() => {
    const sections: { start: number; end: number }[] = [];
    let inPeak = false;
    let peakStart = 0;
    for (const d of densityData) {
      if (d.isPeak && !inPeak) {
        inPeak = true;
        peakStart = d.time - DENSITY_WINDOW_MS / 2;
      } else if (!d.isPeak && inPeak) {
        inPeak = false;
        sections.push({
          start: peakStart,
          end: d.time - DENSITY_WINDOW_MS / 2,
        });
      }
    }
    if (inPeak) {
      sections.push({
        start: peakStart,
        end: totalDurationMs,
      });
    }
    return sections.filter((s) => s.end - s.start > DENSITY_WINDOW_MS * 1.5);
  }, [densityData, totalDurationMs]);

  const visibleNotes = useMemo(() => {
    const viewStart = viewportLeft;
    const viewEnd = viewportLeft + viewportDurationMs;
    return notes.filter(
      (n) =>
        n.time >= viewStart - 500 &&
        (n.type === "long" && n.duration ? n.time + n.duration : n.time) <= viewEnd + 500
    );
  }, [notes, viewportLeft, viewportDurationMs]);

  function timeToX(time: number): number {
    return (time - viewportLeft) * pxPerMs;
  }

  function xToTime(x: number): number {
    return Math.round((x / pxPerMs + viewportLeft) / NOTE_SNAP_MS) * NOTE_SNAP_MS;
  }

  function getNoteX(note: ChartNote): number {
    return (note.time - viewportLeft) * pxPerMs;
  }

  function snapTime(time: number): number {
    return Math.round(time / NOTE_SNAP_MS) * NOTE_SNAP_MS;
  }

  function getTracksAreaRect() {
    const canvasRect = containerRef.current?.getBoundingClientRect();
    const tracksRect = tracksRef.current?.getBoundingClientRect();
    if (!canvasRect || !tracksRect) return null;
    return {
      top: tracksRect.top - canvasRect.top,
      left: tracksRect.left - canvasRect.left,
      width: tracksRect.width,
      height: tracksRect.height,
    };
  }

  function getDensityAreaRect() {
    const canvasRect = containerRef.current?.getBoundingClientRect();
    const densityRect = densityRef.current?.getBoundingClientRect();
    if (!canvasRect || !densityRect) return null;
    return {
      top: densityRect.top - canvasRect.top,
      left: densityRect.left - canvasRect.left,
      width: densityRect.width,
      height: densityRect.height,
    };
  }

  function yToTrack(y: number): number | null {
    const area = getTracksAreaRect();
    if (!area) return null;
    const localY = y - area.top;
    if (localY < 0 || localY >= area.height) return null;
    const track = Math.floor(localY / (area.height / TRACK_COUNT));
    return Math.max(0, Math.min(TRACK_COUNT - 1, track));
  }

  function getNoteYRange(track: number): { top: number; bottom: number } | null {
    const area = getTracksAreaRect();
    if (!area) return null;
    const trackH = area.height / TRACK_COUNT;
    return {
      top: area.top + track * trackH,
      bottom: area.top + (track + 1) * trackH,
    };
  }

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    if (isDraggingNote || isResizingLong) return;

    if (e.button !== 0) return;

    const rect = containerRef.current?.getBoundingClientRect();
    if (!rect) return;

    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const densityArea = getDensityAreaRect();
    if (densityArea && y < densityArea.top + densityArea.height) {
      if (maxLeft <= 0) return;
      setIsDragging(true);
      setDragStartX(e.clientX);
      setDragStartLeft(viewportLeft);
      return;
    }

    const clickedTrack = yToTrack(y);
    if (clickedTrack === null) return;

    const clickedTime = xToTime(x);

    if (currentTool === "add-tap") {
      const newNote: ChartNote = {
        id: Date.now(),
        time: snapTime(clickedTime),
        track: clickedTrack,
        type: "tap",
      };
      setNotes((prev) => [...prev, newNote]);
      setHasUnsavedChanges(true);
      setSelectedNoteId(newNote.id);
    } else if (currentTool === "add-long") {
      const newNote: ChartNote = {
        id: Date.now(),
        time: snapTime(clickedTime),
        track: clickedTrack,
        type: "long",
        duration: 500,
      };
      setNotes((prev) => [...prev, newNote]);
      setHasUnsavedChanges(true);
      setSelectedNoteId(newNote.id);
    } else if (currentTool === "select") {
      setSelectedNoteId(null);
    } else if (currentTool === "delete") {
      setNotes((prev) => prev.filter((n) => {
        const noteX = getNoteX(n);
        const noteWidth = n.type === "long" && n.duration ? n.duration * pxPerMs : 8;
        const yRange = getNoteYRange(n.track);
        if (!yRange) return true;
        return !(
          x >= noteX - 4 &&
          x <= noteX + noteWidth + 4 &&
          y >= yRange.top &&
          y <= yRange.bottom
        );
      }));
      setHasUnsavedChanges(true);
    }
  }, [currentTool, isDraggingNote, isResizingLong, maxLeft, viewportLeft, pxPerMs]);

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    if (isDragging) {
      const deltaX = e.clientX - dragStartX;
      const newLeft = dragStartLeft - deltaX / pxPerMs;
      setViewportLeft(Math.max(0, Math.min(maxLeft, newLeft)));
      return;
    }

    if (isDraggingNote && dragNoteId !== null) {
      const rect = containerRef.current?.getBoundingClientRect();
      if (!rect) return;

      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;

      const newTime = snapTime(xToTime(x) - dragNoteOffset);
      const newTrack = yToTrack(y);
      if (newTrack === null) return;

      setNotes((prev) =>
        prev.map((n) =>
          n.id === dragNoteId
            ? { ...n, time: Math.max(0, Math.min(totalDurationMs, newTime)), track: newTrack }
            : n
        )
      );
      setHasUnsavedChanges(true);
      return;
    }

    if (isResizingLong && resizeNoteId !== null) {
      const rect = containerRef.current?.getBoundingClientRect();
      if (!rect) return;

      const x = e.clientX - rect.left;
      const note = notes.find((n) => n.id === resizeNoteId);
      if (!note || note.type !== "long") return;

      const newEndTime = xToTime(x);
      const newDuration = Math.max(100, newEndTime - note.time);
      const maxDuration = totalDurationMs - note.time;

      setNotes((prev) =>
        prev.map((n) =>
          n.id === resizeNoteId
            ? { ...n, duration: Math.min(newDuration, maxDuration) }
            : n
        )
      );
      setHasUnsavedChanges(true);
    }
  }, [isDragging, dragStartX, dragStartLeft, pxPerMs, maxLeft, isDraggingNote, dragNoteId, isResizingLong, resizeNoteId, notes, totalDurationMs]);

  const handleMouseUp = useCallback(() => {
    setIsDragging(false);
    setIsDraggingNote(false);
    setDragNoteId(null);
    setIsResizingLong(false);
    setResizeNoteId(null);
  }, []);

  const handleNoteMouseDown = useCallback((e: React.MouseEvent, note: ChartNote) => {
    e.stopPropagation();
    if (e.button !== 0) return;

    if (currentTool === "select") {
      setSelectedNoteId(note.id);
      setIsDraggingNote(true);
      setDragNoteId(note.id);
      const rect = containerRef.current?.getBoundingClientRect();
      if (rect) {
        const x = e.clientX - rect.left;
        const noteX = getNoteX(note);
        setDragNoteOffset(xToTime(x) - note.time);
      }
    } else if (currentTool === "delete") {
      setNotes((prev) => prev.filter((n) => n.id !== note.id));
      setHasUnsavedChanges(true);
    }
  }, [currentTool]);

  const handleLongNoteEndMouseDown = useCallback((e: React.MouseEvent, note: ChartNote) => {
    e.stopPropagation();
    if (e.button !== 0) return;

    if (currentTool === "select" && note.type === "long") {
      setSelectedNoteId(note.id);
      setIsResizingLong(true);
      setResizeNoteId(note.id);
    }
  }, [currentTool]);

  useEffect(() => {
    const handleGlobalMouseUp = () => {
      setIsDragging(false);
      setIsDraggingNote(false);
      setDragNoteId(null);
      setIsResizingLong(false);
      setResizeNoteId(null);
    };
    window.addEventListener("mouseup", handleGlobalMouseUp);
    return () => window.removeEventListener("mouseup", handleGlobalMouseUp);
  }, []);

  function handleZoomIn() {
    if (!canZoomIn) return;
    const newSeconds = ZOOM_LEVELS[viewportZoomIndex - 1];
    setViewportSeconds(newSeconds);
  }

  function handleZoomOut() {
    if (!canZoomOut) return;
    const newSeconds = ZOOM_LEVELS[viewportZoomIndex + 1];
    setViewportSeconds(newSeconds);
  }

  function handleSave() {
    const normalizedNotes = normalizeChartNotes(notes);
    let updatedChart: Chart = {
      ...chart,
      notes: normalizedNotes,
      difficulty,
    };
    updatedChart = recalculateChartStats(updatedChart);

    const validation = validateChart(updatedChart, totalDurationMs);
    if (!validation.valid) {
      setValidationErrors(validation.errors);
      setShowValidation(true);
      return;
    }

    saveCustomChart(updatedChart);
    setChart(updatedChart);
    setNotes(normalizedNotes);
    setHasUnsavedChanges(false);
    setValidationErrors([]);
    setShowValidation(false);
  }

  function handleRestoreAuto() {
    if (!window.confirm("确定要恢复为自动生成的谱面吗？所有编辑将丢失。")) {
      return;
    }
    const autoChart = restoreAutoGeneratedChart(songId, difficulty);
    setChart(autoChart);
    setNotes([...autoChart.notes]);
    setHasUnsavedChanges(false);
    setSelectedNoteId(null);
    setValidationErrors([]);
    setShowValidation(false);
  }

  function handleResetToAuto() {
    if (!window.confirm("确定要重新加载自动生成的谱面吗？当前未保存的编辑将丢失。")) {
      return;
    }
    const autoChart = getAutoGeneratedChart(songId, difficulty);
    setChart(autoChart);
    setNotes([...autoChart.notes]);
    setHasUnsavedChanges(false);
    setSelectedNoteId(null);
  }

  function handleDeleteSelected() {
    if (selectedNoteId === null) return;
    setNotes((prev) => prev.filter((n) => n.id !== selectedNoteId));
    setSelectedNoteId(null);
    setHasUnsavedChanges(true);
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === "Delete" || e.key === "Backspace") {
      if (selectedNoteId !== null) {
        e.preventDefault();
        handleDeleteSelected();
      }
    } else if (e.key === "Escape") {
      setSelectedNoteId(null);
      setCurrentTool("select");
    } else if (e.key === "1") {
      setCurrentTool("select");
    } else if (e.key === "2") {
      setCurrentTool("add-tap");
    } else if (e.key === "3") {
      setCurrentTool("add-long");
    } else if (e.key === "4") {
      setCurrentTool("delete");
    }
  }

  const selectedNote = selectedNoteId !== null ? notes.find((n) => n.id === selectedNoteId) : null;
  const isCustom = isChartCustom(songId, difficulty);
  const diffInfo = CHART_DIFFICULTY_INFO[difficulty];

  const trackHeight = 40;
  const densityHeight = 36;
  const headerHeight = 36;

  if (!song) {
    return <div>歌曲未找到</div>;
  }

  return (
    <div className="chart-editor" onKeyDown={handleKeyDown} tabIndex={0}>
      <div className="editor-header">
        <div className="editor-header-left">
          <button className="back-btn" onClick={onBack}>
            ← 返回
          </button>
          <div>
            <h2 className="editor-title">谱面编辑器</h2>
            <p className="editor-subtitle">
              {song.title} · {isCustom ? "自定义谱面" : "自动生成谱面"}
            </p>
          </div>
        </div>

        <div className="editor-header-right">
          <div className="difficulty-switcher small">
            {CHART_DIFFICULTIES.map((diff) => {
              const info = CHART_DIFFICULTY_INFO[diff];
              const isActive = difficulty === diff;
              return (
                <button
                  key={diff}
                  className={`difficulty-switch-btn small ${isActive ? "active" : ""}`}
                  style={{ ["--color" as any]: info.color } as React.CSSProperties}
                  onClick={() => {
                    if (hasUnsavedChanges) {
                      if (!window.confirm("切换难度将丢失未保存的更改，确定继续？")) {
                        return;
                      }
                    }
                    setDifficulty(diff);
                  }}
                >
                  {info.label}
                </button>
              );
            })}
          </div>

          {hasUnsavedChanges && (
            <span className="unsaved-badge">● 未保存</span>
          )}

          <button
            className="ghost-btn"
            onClick={handleResetToAuto}
            title="重新加载自动生成谱面"
          >
            ↺ 重置
          </button>

          <button
            className="ghost-btn danger-btn"
            onClick={handleRestoreAuto}
            title="恢复为自动生成谱面"
          >
            🗑️ 恢复自动
          </button>

          <button
            className="start-btn"
            onClick={handleSave}
            disabled={!hasUnsavedChanges}
            style={{
              background: hasUnsavedChanges
                ? `linear-gradient(135deg, ${diffInfo.color}, ${song.accentColor})`
                : undefined,
            }}
          >
            💾 保存
          </button>
        </div>
      </div>

      <div className="editor-toolbar">
        <div className="tool-group">
          <button
            className={`tool-btn ${currentTool === "select" ? "active" : ""}`}
            onClick={() => setCurrentTool("select")}
            title="选择/移动 (1)"
          >
            🖱️ 选择
          </button>
          <button
            className={`tool-btn ${currentTool === "add-tap" ? "active" : ""}`}
            onClick={() => setCurrentTool("add-tap")}
            title="添加点击音符 (2)"
          >
            👆 点击
          </button>
          <button
            className={`tool-btn ${currentTool === "add-long" ? "active" : ""}`}
            onClick={() => setCurrentTool("add-long")}
            title="添加长按音符 (3)"
          >
            🖱️ 长按
          </button>
          <button
            className={`tool-btn ${currentTool === "delete" ? "active" : ""}`}
            onClick={() => setCurrentTool("delete")}
            title="删除音符 (4)"
          >
            🗑️ 删除
          </button>
        </div>

        <div className="tool-group">
          <button
            className={`zoom-btn ${!canZoomIn ? "disabled" : ""}`}
            onClick={handleZoomIn}
            disabled={!canZoomIn}
          >
            +
          </button>
          <span className="zoom-label">{viewportSeconds}s</span>
          <button
            className={`zoom-btn ${!canZoomOut ? "disabled" : ""}`}
            onClick={handleZoomOut}
            disabled={!canZoomOut}
          >
            −
          </button>
        </div>

        {selectedNote && (
          <div className="selected-note-info">
            <span>选中 #{selectedNote.id}</span>
            <span>{selectedNote.type === "tap" ? "点击" : "长按"}</span>
            <span>轨道 {selectedNote.track + 1}</span>
            <span>{formatDuration(Math.floor(selectedNote.time / 1000))}</span>
            {selectedNote.type === "long" && selectedNote.duration && (
              <span>时长 {selectedNote.duration}ms</span>
            )}
            <button className="ghost-btn small-btn danger-btn" onClick={handleDeleteSelected}>
              删除
            </button>
          </div>
        )}
      </div>

      <div className="editor-content">
        <div className="editor-main">
          <div
            className={`editor-canvas ${isDragging ? "dragging" : ""} ${isDraggingNote ? "dragging-note" : ""} tool-${currentTool}`}
            ref={containerRef}
            onMouseDown={handleMouseDown}
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
            onMouseLeave={handleMouseUp}
          >
            <div className="canvas-header" style={{ height: headerHeight }}>
              <div className="section-label">难度密度</div>
            </div>

            <div className="density-section" style={{ height: densityHeight }} ref={densityRef}>
              <div className="density-chart" style={{ height: densityHeight }}>
                {peakSections.map((section, i) => {
                  const x = timeToX(section.start);
                  const width = (section.end - section.start) * pxPerMs;
                  if (x + width < 0 || x > containerWidth) return null;
                  return (
                    <div
                      key={i}
                      className="peak-section"
                      style={{
                        left: `${Math.max(0, x)}px`,
                        width: `${Math.min(width, containerWidth - Math.max(0, x))}px`,
                        background: `linear-gradient(180deg, ${song.coverColor}33, ${song.accentColor}22)`,
                        borderLeft: `1px solid ${song.accentColor}66`,
                        borderRight: `1px solid ${song.accentColor}66`,
                      }}
                    />
                  );
                })}
                <svg
                  className="density-svg"
                  width="100%"
                  height={densityHeight}
                  preserveAspectRatio="none"
                >
                  <defs>
                    <linearGradient id="editorDensityGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor={song.accentColor} stopOpacity="0.8" />
                      <stop offset="100%" stopColor={song.coverColor} stopOpacity="0.2" />
                    </linearGradient>
                  </defs>
                  <path
                    d={densityData
                      .map((d, i) => {
                        const x = timeToX(d.time);
                        const y = densityHeight * (1 - d.density * 0.85 - 0.1);
                        return `${i === 0 ? "M" : "L"} ${x} ${y}`;
                      })
                      .join(" ") + ` L ${timeToX(totalDurationMs)} ${densityHeight} L ${timeToX(0)} ${densityHeight} Z`}
                    fill="url(#editorDensityGradient)"
                  />
                </svg>
              </div>
            </div>

            <div className="tracks-header" style={{ height: headerHeight }}>
              <div className="section-label">轨道分布</div>
            </div>

            <div
              className="editor-tracks"
              style={{ height: trackHeight * TRACK_COUNT }}
              ref={tracksRef}
            >
              {Array.from({ length: TRACK_COUNT }).map((_, trackIdx) => (
                <div
                  key={trackIdx}
                  className={`editor-track ${currentTool === "add-tap" || currentTool === "add-long" ? "add-mode" : ""}`}
                  style={{
                    height: trackHeight,
                    borderBottom:
                      trackIdx < TRACK_COUNT - 1
                        ? "1px solid rgba(148, 163, 184, 0.12)"
                        : "none",
                  }}
                  data-track={trackIdx}
                >
                  <div
                    className="track-indicator"
                    style={{ backgroundColor: TRACK_COLORS[trackIdx] + "33" }}
                  >
                    {trackIdx + 1}
                  </div>
                </div>
              ))}

              {visibleNotes.map((note) => {
                const x = getNoteX(note);
                if (x < -100 || x > containerWidth + 100) return null;

                const noteWidth = note.type === "long" && note.duration
                  ? Math.max(8, note.duration * pxPerMs)
                  : 8;
                const isSelected = note.id === selectedNoteId;

                return (
                  <div
                    key={note.id}
                    className={`editor-note ${note.type} ${isSelected ? "selected" : ""} ${dragNoteId === note.id ? "dragging" : ""}`}
                    style={{
                      left: `${x}px`,
                      top: `${note.track * trackHeight + trackHeight / 2 - 8}px`,
                      width: `${noteWidth}px`,
                      height: note.type === "long" ? "16px" : "16px",
                      backgroundColor: TRACK_COLORS[note.track],
                      borderRadius: note.type === "long" ? "4px" : "50%",
                      boxShadow: isSelected
                        ? `0 0 0 3px #fff, 0 0 16px ${TRACK_COLORS[note.track]}`
                        : `0 0 8px ${TRACK_COLORS[note.track]}80`,
                    }}
                    onMouseDown={(e) => handleNoteMouseDown(e, note)}
                  >
                    {note.type === "long" && (
                      <div
                        className="long-note-resize-handle"
                        onMouseDown={(e) => handleLongNoteEndMouseDown(e, note)}
                        title="拖动调整时长"
                      />
                    )}
                  </div>
                );
              })}
            </div>

            <div className="time-axis">
              {Array.from({ length: Math.ceil(song.duration / 10) + 1 }).map((_, i) => {
                const time = i * 10 * 1000;
                const x = timeToX(time);
                if (x < -20 || x > containerWidth + 20) return null;
                return (
                  <div key={i} className="time-tick" style={{ left: `${x}px` }}>
                    <div className="tick-line" />
                    <span className="tick-label">{formatDuration(i * 10)}</span>
                  </div>
                );
              })}
            </div>

            <div className="playhead" style={{ left: `${timeToX(0)}px` }} />
          </div>

          <div className="editor-scrollbar">
            <div className="scrollbar-track">
              <div
                className="scrollbar-thumb"
                style={{
                  left: `${(viewportLeft / totalDurationMs) * 100}%`,
                  width: `${(viewportDurationMs / totalDurationMs) * 100}%`,
                  background: `linear-gradient(90deg, ${song.coverColor}, ${song.accentColor})`,
                }}
              />
            </div>
          </div>
        </div>

        <div className="editor-sidebar">
          <div className="stats-panel">
            <h3 className="panel-title">实时统计</h3>

            <div className="stats-grid">
              <div className="stat-card">
                <span className="stat-card-label">总音符</span>
                <span className="stat-card-value">{stats.totalNotes}</span>
              </div>
              <div className="stat-card">
                <span className="stat-card-label">点击</span>
                <span className="stat-card-value">{stats.tapNotes}</span>
              </div>
              <div className="stat-card">
                <span className="stat-card-label">长按</span>
                <span className="stat-card-value">{stats.longNotes}</span>
              </div>
              <div className="stat-card">
                <span className="stat-card-label">密度</span>
                <span className="stat-card-value">{stats.density}/s</span>
              </div>
            </div>

            <div className="track-distribution">
              <h4 className="panel-subtitle">轨道分布</h4>
              <div className="track-bars">
                {stats.trackDistribution.map((count, idx) => {
                  const maxCount = Math.max(...stats.trackDistribution, 1);
                  const percent = maxCount > 0 ? (count / maxCount) * 100 : 0;
                  return (
                    <div key={idx} className="track-bar-row">
                      <span
                        className="track-bar-label"
                        style={{ color: TRACK_COLORS[idx] }}
                      >
                        轨道 {idx + 1}
                      </span>
                      <div className="track-bar-container">
                        <div
                          className="track-bar-fill"
                          style={{
                            width: `${percent}%`,
                            backgroundColor: TRACK_COLORS[idx],
                          }}
                        />
                      </div>
                      <span className="track-bar-count">{count}</span>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="note-type-distribution">
              <h4 className="panel-subtitle">类型分布</h4>
              <div className="type-pie">
                <div
                  className="type-pie-segment tap"
                  style={{
                    background: `conic-gradient(
                      #06b6d4 0deg,
                      #06b6d4 ${stats.totalNotes > 0 ? (stats.tapNotes / stats.totalNotes) * 360 : 0}deg,
                      #f97316 ${stats.totalNotes > 0 ? (stats.tapNotes / stats.totalNotes) * 360 : 0}deg,
                      #f97316 360deg
                    )`,
                  }}
                />
                <div className="type-pie-center">
                  <span>{stats.totalNotes}</span>
                </div>
              </div>
              <div className="type-legend">
                <div className="legend-item">
                  <span className="legend-dot" style={{ backgroundColor: "#06b6d4" }} />
                  <span>点击 {stats.tapNotes}</span>
                </div>
                <div className="legend-item">
                  <span className="legend-dot" style={{ backgroundColor: "#f97316" }} />
                  <span>长按 {stats.longNotes}</span>
                </div>
              </div>
            </div>

            <div className="density-info">
              <h4 className="panel-subtitle">高潮段</h4>
              <div className="peak-count">
                <span className="peak-icon">🔥</span>
                <span>{peakSections.length} 个高潮段</span>
              </div>
            </div>
          </div>

          {showValidation && validationErrors.length > 0 && (
            <div className="validation-panel">
              <h3 className="panel-title error-title">⚠️ 验证错误</h3>
              <div className="validation-errors">
                {validationErrors.map((error, idx) => (
                  <div key={idx} className={`validation-error error-${error.type}`}>
                    <span className="error-icon">
                      {error.type === "time" ? "⏱️" :
                       error.type === "track" ? "📍" :
                       error.type === "duration" ? "📏" : "⚠️"}
                    </span>
                    <span className="error-message">{error.message}</span>
                  </div>
                ))}
              </div>
              <button
                className="ghost-btn small-btn"
                onClick={() => setShowValidation(false)}
              >
                关闭
              </button>
            </div>
          )}

          <div className="help-panel">
            <h3 className="panel-title">操作说明</h3>
            <ul className="help-list">
              <li><kbd>1</kbd> 选择工具：拖动移动音符</li>
              <li><kbd>2</kbd> 点击工具：点击添加点击音符</li>
              <li><kbd>3</kbd> 长按工具：点击添加长按音符</li>
              <li><kbd>4</kbd> 删除工具：点击删除音符</li>
              <li><kbd>Del</kbd> 删除选中音符</li>
              <li><kbd>Esc</kbd> 取消选择</li>
              <li>拖动长按音符右端调整时长</li>
              <li>在密度图上拖动可滚动时间轴</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
