import type { Chart, ChartDifficulty, ChartNote, ChartValidationResult, ChartValidationError } from "./types";
import { resourceManager, CHART_DIFFICULTIES, CHART_DIFFICULTY_INFO } from "./resourceManager";

export { CHART_DIFFICULTIES, CHART_DIFFICULTY_INFO };

const TRACK_COUNT = 4;
const MIN_NOTE_DURATION_MS = 100;
const MIN_NOTE_GAP_MS = 50;

export function getChartForSong(songId: string, difficulty: ChartDifficulty = "standard"): Chart {
  return resourceManager.getChart(songId, difficulty);
}

export function rebuildChartForSong(songId: string, difficulty: ChartDifficulty = "standard"): Chart {
  return resourceManager.rebuildChart(songId, difficulty);
}

export function rebuildAllChartsForSong(songId: string): void {
  resourceManager.rebuildAllChartsForSong(songId);
}

export function isChartCustom(songId: string, difficulty: ChartDifficulty = "standard"): boolean {
  return resourceManager.isChartCustom(songId, difficulty);
}

export function saveCustomChart(chart: Chart): void {
  resourceManager.saveCustomChart(chart);
}

export function restoreAutoGeneratedChart(songId: string, difficulty: ChartDifficulty = "standard"): Chart {
  return resourceManager.restoreAutoGeneratedChart(songId, difficulty);
}

export function getAutoGeneratedChart(songId: string, difficulty: ChartDifficulty = "standard"): Chart {
  return resourceManager.getAutoGeneratedChart(songId, difficulty);
}

export function validateChart(chart: Chart, totalDurationMs: number): ChartValidationResult {
  const errors: ChartValidationError[] = [];
  const sortedNotes = [...chart.notes].sort((a, b) => a.time - b.time);

  for (const note of sortedNotes) {
    if (note.time < 0 || note.time > totalDurationMs) {
      errors.push({
        type: "time",
        noteId: note.id,
        message: `音符 #${note.id} 时间 ${note.time}ms 超出歌曲范围 (0-${totalDurationMs}ms)`,
      });
    }

    if (note.track < 0 || note.track >= TRACK_COUNT) {
      errors.push({
        type: "track",
        noteId: note.id,
        message: `音符 #${note.id} 轨道 ${note.track} 超出范围 (0-${TRACK_COUNT - 1})`,
      });
    }

    if (note.type === "long") {
      if (!note.duration || note.duration < MIN_NOTE_DURATION_MS) {
        errors.push({
          type: "duration",
          noteId: note.id,
          message: `长按音符 #${note.id} 时长不足 ${MIN_NOTE_DURATION_MS}ms`,
        });
      } else {
        const endTime = note.time + note.duration;
        if (endTime > totalDurationMs) {
          errors.push({
            type: "duration",
            noteId: note.id,
            message: `长按音符 #${note.id} 尾部 ${endTime}ms 超出歌曲范围`,
          });
        }
      }
    }
  }

  const trackIntervals: Record<number, { start: number; end: number; noteId: number }[]> = {};
  for (let i = 0; i < TRACK_COUNT; i++) {
    trackIntervals[i] = [];
  }

  for (const note of sortedNotes) {
    if (note.track < 0 || note.track >= TRACK_COUNT) continue;

    const noteEnd = note.type === "long" && note.duration
      ? note.time + note.duration
      : note.time;

    const intervals = trackIntervals[note.track];
    for (const interval of intervals) {
      const overlapStart = Math.max(note.time, interval.start);
      const overlapEnd = Math.min(noteEnd, interval.end);
      if (overlapEnd - overlapStart > -MIN_NOTE_GAP_MS) {
        if (note.id !== interval.noteId) {
          errors.push({
            type: "overlap",
            noteId: note.id,
            message: `轨道 ${note.track + 1} 上音符 #${note.id} 与 #${interval.noteId} 重叠或间隔不足 ${MIN_NOTE_GAP_MS}ms`,
          });
        }
      }
    }

    intervals.push({
      start: note.time - MIN_NOTE_GAP_MS,
      end: noteEnd + MIN_NOTE_GAP_MS,
      noteId: note.id,
    });
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

export function normalizeChartNotes(notes: ChartNote[]): ChartNote[] {
  const sorted = [...notes].sort((a, b) => a.time - b.time);
  return sorted.map((note, idx) => ({ ...note, id: idx }));
}

export function recalculateChartStats(chart: Chart): Chart {
  const notes = chart.notes;
  const totalTapNotes = notes.filter((n) => n.type === "tap").length;
  const totalLongNotes = notes.filter((n) => n.type === "long").length;

  const DENSITY_WINDOW_MS = 2000;
  const totalDuration = notes.length > 0
    ? Math.max(...notes.map((n) => n.type === "long" && n.duration ? n.time + n.duration : n.time))
    : 0;

  const windows: { time: number; count: number }[] = [];
  const step = DENSITY_WINDOW_MS / 2;
  for (let t = 0; t < totalDuration; t += step) {
    const windowStart = t;
    const windowEnd = t + DENSITY_WINDOW_MS;
    let count = 0;
    for (const note of notes) {
      if (note.time >= windowStart && note.time < windowEnd) {
        count++;
      }
    }
    windows.push({ time: t + DENSITY_WINDOW_MS / 2, count });
  }
  const maxCount = Math.max(...windows.map((w) => w.count), 1);
  const densityData = windows.map((w) => ({
    time: w.time,
    density: w.count / maxCount,
    isPeak: w.count / maxCount > 0.7,
  }));

  const sections: { start: number; end: number }[] = [];
  let inPeak = false;
  let peakStart = 0;
  for (const d of densityData) {
    if (d.isPeak && !inPeak) {
      inPeak = true;
      peakStart = d.time - DENSITY_WINDOW_MS / 2;
    } else if (!d.isPeak && inPeak) {
      inPeak = false;
      sections.push({
        start: peakStart,
        end: d.time - DENSITY_WINDOW_MS / 2,
      });
    }
  }
  if (inPeak) {
    sections.push({
      start: peakStart,
      end: totalDuration,
    });
  }
  const chorusCount = sections.filter((s) => s.end - s.start > DENSITY_WINDOW_MS * 1.5).length;

  return {
    ...chart,
    totalNotes: notes.length,
    totalTapNotes,
    totalLongNotes,
    chorusCount,
  };
}
